// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlk7t20OhsbJQZZ3TmaCeg_XLm6uSrf24',
    appId: '1:775832848082:web:e0ac5dccc562c6df524f0b',
    messagingSenderId: '775832848082',
    projectId: 'social-media-app-9e0a2',
    authDomain: 'social-media-app-9e0a2.firebaseapp.com',
    storageBucket: 'social-media-app-9e0a2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAg2Bg3OzDotmYVNMa-XguQ830Brrr1Snw',
    appId: '1:775832848082:android:6de59c78b109bcaf524f0b',
    messagingSenderId: '775832848082',
    projectId: 'social-media-app-9e0a2',
    storageBucket: 'social-media-app-9e0a2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqchma6Cwr1Fjz7NWc5aNeRsnjrn8jsk8',
    appId: '1:775832848082:ios:09bd42ce35c90c02524f0b',
    messagingSenderId: '775832848082',
    projectId: 'social-media-app-9e0a2',
    storageBucket: 'social-media-app-9e0a2.appspot.com',
    iosClientId: '775832848082-peei9187ms75p9jomcrk50a1hcp8ubcm.apps.googleusercontent.com',
    iosBundleId: 'com.example.fetaSocialMedia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqchma6Cwr1Fjz7NWc5aNeRsnjrn8jsk8',
    appId: '1:775832848082:ios:d67260bf92ff60a0524f0b',
    messagingSenderId: '775832848082',
    projectId: 'social-media-app-9e0a2',
    storageBucket: 'social-media-app-9e0a2.appspot.com',
    iosBundleId: 'com.example.fetaSocialMedia.RunnerTests',
  );
}
